version: '3.8'
services:
  emqx:
    image: emqx/emqx:5.1.6
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT TCP
      - "8083:8083"    # MQTT WebSocket
      - "8084:8084"    # MQTT Secure WebSocket (wss)
      - "8883:8883"    # MQTT Secure TCP
      - "18083:18083"  # EMQX Dashboard
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public

  frontend:
    image: node:24
    container_name: front-end
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    expose:
      - "3000"
    ports:
      - "3000:3000"


